### ISSUE TITLE
Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.ts

### ISSUE THREAD

**Issue by CamilleHbp** [potreco/viterc#3]
Hello! 

I'm using the latest template but I get this error message from jest. I've tried adding `types = [ "@testing-library/jest-dom" ]` to `tsconfig.json` but that actually had a worse effect (`expect` was not recognised). I'd love some pointers on how to fix this? Thanks for the nice template! :) 
 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/11173924/183252743-80342129-b193-46f7-8275-fa5f5c8784c8.png">

**Comment by potreco** [comment]
Hello @CamilleHbp, how are you?

Thanks for you feedback about the project.

I clone the project from scratch and installed all the dependencies (`yarn install`) and i had no problem with the Jest.
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/8931135/183260945-a6e241f8-7e2b-47e5-92d4-035c3385beca.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/8931135/183261197-ae9bc3cc-b298-4089-9f3a-efb480ed34d1.png">

I found an error related to relative imports and Jest, i will fix this now, but i don't believe this interfere with the types

Do you make any changes on the `package.json` or any other file?  Can you post it?

Thanks! :)

**Comment by potreco** [comment]
Hello @CamilleHbp, i will close this issue because the questions were not answered.

If you need assistance, feel free to create a new issue or reopen this.

See ya! :)

**Comment by CamilleHbp** [comment]
Thank you @potreco ! I'm very sorry that I did not answer... I just noticed the notification icon in Github and am now in the process of answering all unseen notifications. Sorry about that. I'm not using your template anymore since I decided to create mine to learn Vite the proper way :) Have a nice day!
