### ISSUE TITLE
Relative paths don't working with Jest

### ISSUE THREAD

**Issue by potreco** [potreco/viterc#4]
Some relative paths is not working with Jest.

Default Jest configuration on project:
```
module.exports = {
  testEnvironment: "jsdom",
  transform: {
    "^.+\\.tsx?$": "ts-jest"
  },
  moduleNameMapper: {
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/test/__mocks__/fileMock.js',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    "^@/(.*)$": "<rootDir>/src/$1"
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
}
```
This configuration is causing the error below:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/8931135/183261465-8fbe96e3-31e3-49e5-acad-360877c493bc.png">

## Solutions:
* Documentation orientation;
* Pre send a file with `@/Components/` relative path.

**Comment by lucasluca** [comment]
still having this issue when running on Github actions, but locally it works normal

**Comment by potreco** [comment]
Hello @lucasluca 

Can you open a issue with some prints and informations about this problem?

Thanks! :)
